name: nightly

on:
  workflow_dispatch:
  schedule:
    # 8 PM UTC every day
    - cron: "0 20 * * *"


# Don't allow concurrent runs of workflows deploying to same target
concurrency:
  group: build-and-deploy-to-${{ vars.DEPLOY_URL }}
  cancel-in-progress: false

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        DEB_DISTRO: [jammy, noble]
        ARCH: [x64, arm64]
    uses: ./.github/workflows/build.yaml
    with:
      DEB_DISTRO: ${{ matrix.DEB_DISTRO }}
      ARCH: ${{ matrix.ARCH }}
      ROS_SOURCES: gazebo.repos ros-one.repos
      INSTALL_GPG_KEYS: |
        sudo curl -sSL https://ros.packages.techfak.net/gpg.key -o /etc/apt/keyrings/ros-one-keyring.gpg
      EXTRA_DEB_SOURCES: "deb [signed-by=/etc/apt/keyrings/ros-one-keyring.gpg] https://ros.packages.techfak.net ${{matrix.DEB_DISTRO}}-testing main"
      EXTRA_ROSDEP_SOURCES: |
        rosdep.yaml
        https://ros.packages.techfak.net/ros-one.yaml
      # proceed from existing debs artifact if run_attempt > 1
      DOWNLOAD_DEBS: ${{ github.run_attempt != '1' }}
      DEBS_ARTIFACT_NAME: ${{ matrix.DEB_DISTRO }}-${{ matrix.ARCH }}-debs
      SKIP_EXISTING: true
      SKIP_KNOWN_FAILING: true
      CONTINUE_ON_ERROR: true
      INSTALL_TO_CHROOT: false

  deploy:
    needs: build
    if: ${{ !cancelled() && vars.DEPLOY_URL }}
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Import build artifacts to reprepro server
        uses: ./reprepro
        with:
          url: "${{ vars.DEPLOY_URL }}?run_id=${{ github.run_id }}"
