name: splitted

on:
  workflow_dispatch:
    inputs:
      DEB_DISTRO:
        type: string
        required: true
        description: 'Ubuntu/Debian distro:'
        default: jammy

      PUSH_MODE:
        type: choice
        description: Push to DEPLOY_URL?
        required: true
        default: skip
        options:
          - skip
          - push
          - amend
          - squash

jobs:
  robot:
    uses: ubi-agni/ros-builder-action/.github/workflows/build.yaml@main
    with:
      ROS_SOURCES: 1-robot.repos
      DEB_DISTRO: ${{ inputs.DEB_DISTRO }}
      ROS_DISTRO: one
      DOWNLOAD_DEBS: ${{ github.run_attempt != '1' }}

  desktop:
    needs: robot
    uses: ubi-agni/ros-builder-action/.github/workflows/build.yaml@main
    with:
      ROS_SOURCES: 2-desktop.repos
      DEB_DISTRO: ${{ inputs.DEB_DISTRO }}
      ROS_DISTRO: one
      DOWNLOAD_DEBS: true

  desktop-full:
    needs: desktop
    uses: ubi-agni/ros-builder-action/.github/workflows/build.yaml@main
    with:
      ROS_SOURCES: 3-desktop-full.repos
      DEB_DISTRO: ${{ inputs.DEB_DISTRO }}
      ROS_DISTRO: one
      DOWNLOAD_DEBS: true

  deploy:
    needs: desktop-full
    if: always() && ( inputs.PUSH_MODE != 'skip' ) && vars.DEPLOY_URL
    uses: ubi-agni/ros-builder-action/.github/workflows/deploy.yaml@main
    with:
      CONTENT_MODE: replace
      PUSH_MODE: ${{ inputs.PUSH_MODE || vars.PUSH_MODE }}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
